/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-29 12:24:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.client.donation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.friendly.eco.util.DateManager;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.Date;
import com.friendly.eco.domain.Dcontents;
import java.util.List;
import com.friendly.eco.domain.Mem;

public final class donationList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/views/client/donation/../inc/spinner.jsp", Long.valueOf(1679398328000L));
    _jspx_dependants.put("/WEB-INF/views/client/donation/../inc/header_link.jsp", Long.valueOf(1680152882000L));
    _jspx_dependants.put("/WEB-INF/views/client/donation/../inc/navbar.jsp", Long.valueOf(1679650916000L));
    _jspx_dependants.put("/WEB-INF/views/client/donation/../inc/capyright.jsp", Long.valueOf(1679398328000L));
    _jspx_dependants.put("/WEB-INF/views/client/donation/../inc/back_to_top.jsp", Long.valueOf(1679398328000L));
    _jspx_dependants.put("/WEB-INF/views/client/donation/../inc/footer_link.jsp", Long.valueOf(1680152976000L));
    _jspx_dependants.put("/WEB-INF/views/client/donation/../inc/topbar.jsp", Long.valueOf(1680176358000L));
    _jspx_dependants.put("/WEB-INF/views/client/donation/../inc/footer.jsp", Long.valueOf(1679398328000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.friendly.eco.domain.Dcontents");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.friendly.eco.util.DateManager");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("org.springframework.beans.factory.annotation.Autowired");
    _jspx_imports_classes.add("com.friendly.eco.domain.Mem");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<title>진행중인 기부</title>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<!-- header_link Start -->\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("    <title>EcoEco</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- challenge detail  Start-->\r\n");
      out.write("	<!-- Google Font -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Cookie&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	 <!-- Css Styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/font-awesome.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/elegant-icons.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/jquery-ui.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/magnific-popup.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/owl.carousel.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/slicknav.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/style.css\" type=\"text/css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- challenge detail  End-->\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@700&family=Open+Sans:wght@400;500;600&display=swap\" rel=\"stylesheet\">   \r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"/resources/client/lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/resources/client/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/resources/client/lib/lightbox/css/lightbox.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"/resources/client/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"/resources/client/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- summernote -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/client/plugins/summernote/summernote-bs4.min.css\">\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!-- header_link End -->\r\n");
      out.write("	<!-- include libraries(jQuery, bootstrap) -->\r\n");
      out.write("<!-- <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\" rel=\"stylesheet\">  -->\r\n");
      out.write("	<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("	<!-- <script src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script> -->\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#thumimg {\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sort {\r\n");
      out.write("	/* float: left; */\r\n");
      out.write("	float: right;\r\n");
      out.write("	width: 140px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#contents {\r\n");
      out.write("	/* float: left; */\r\n");
      out.write("	margin: 10px;\r\n");
      out.write("	width: 300px;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- Spinner Start -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    <!-- Spinner Start -->\r\n");
      out.write("    <div id=\"spinner\" class=\"show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center\">\r\n");
      out.write("        <div class=\"spinner-border text-primary\" role=\"status\" style=\"width: 3rem; height: 3rem;\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Topbar Start -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Topbar Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-dark px-0\">\r\n");
      out.write("        <div class=\"row g-0 d-none d-lg-flex\">\r\n");
      out.write("            <div class=\"col-lg-6 ps-5 text-start\">\r\n");
      out.write("                <div class=\"h-100 d-inline-flex align-items-center text-light\">\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("             <div class=\"col-lg-6 text-end\">\r\n");
      out.write("             ");
if(session.getAttribute("mem")==null){
      out.write("\r\n");
      out.write("                <a class=\"btn btn-link text-light\" id=\"a_login\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                <div class=\"h-100 bg-secondary d-inline-flex align-items-center text-dark py-2 px-4\">\r\n");
      out.write("                    <a href=\"#\" id=\"bt_goRegist\"><span class=\"me-2 fw-semi-bold\">회원가입</span></a>\r\n");
      out.write("              ");
}else{
      out.write("    \r\n");
      out.write("              ");

                     Mem mem=(Mem)session.getAttribute("mem");
               
      out.write("\r\n");
      out.write("                <a class=\"btn btn-link text-light\" id=\"bt_logout\"><b>Logout</b></i></a>\r\n");
      out.write("                <div class=\"h-100 bg-secondary d-inline-flex align-items-center text-dark py-2 px-4\">\r\n");
      out.write("                    <a href=\"#\" id=\"bt_goMypage\"><span class=\"me-2 fw-semi-bold\">");
      out.print(mem.getMem_id() );
      out.write("님</span></a>\r\n");
      out.write("               ");
} 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Navbar Start -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!-- Navbar Start -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5\">\r\n");
      out.write("        <a href=\"/\" class=\"navbar-brand d-flex align-items-center\">\r\n");
      out.write("            <img src=\"/resources/client/img/EcoHomeLogo.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <button type=\"button\" class=\"navbar-toggler me-0\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\r\n");
      out.write("            <div class=\"navbar-nav ms-auto p-4 p-lg-0\">\r\n");
      out.write("             \r\n");
      out.write("                <div class=\"nav-item dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link\" data-bs-toggle=\"dropdown\">소개</a>\r\n");
      out.write("                    <div class=\"dropdown-menu bg-light m-0\">\r\n");
      out.write("                        <a href=\"gallery.html\" class=\"dropdown-item\">회사소개</a>\r\n");
      out.write("                        <a href=\"team_member.jsp\" class=\"dropdown-item\">팀원소개</a>\r\n");
      out.write("                        <a href=\"feature.html\" class=\"dropdown-item\">유관기관</a>\r\n");
      out.write("                        <a href=\"team.html\" class=\"dropdown-item\">기업 후원 안내</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav-item dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link\" data-bs-toggle=\"dropdown\">챌린지</a>\r\n");
      out.write("                    <div class=\"dropdown-menu bg-light m-0\">\r\n");
      out.write("                        <a href=\"/challenge/list\" class=\"dropdown-item\">공식 챌린지</a>\r\n");
      out.write("                        <a href=\"team.html\" class=\"dropdown-item\">sns 챌린지</a>\r\n");
      out.write("                        <a href=\"testimonial.html\" class=\"dropdown-item\">콜라보 챌린지</a>\r\n");
      out.write("                        <a href=\"404.html\" class=\"dropdown-item\">유저 챌린지</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav-item dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link\" data-bs-toggle=\"dropdown\">후원</a>\r\n");
      out.write("                    <div class=\"dropdown-menu bg-light m-0\">\r\n");
      out.write("                        <a href=\"/donation/donationMain\" class=\"dropdown-item\">기부</a>\r\n");
      out.write("                        <a href=\"/funding/fundingMain\" class=\"dropdown-item\">펀딩</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav-item dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link\" data-bs-toggle=\"dropdown\">커뮤니티</a>\r\n");
      out.write("                    <div class=\"dropdown-menu bg-light m-0\">\r\n");
      out.write("                        <a href=\"/community/chatterList\" class=\"dropdown-item\">에코 수다</a>\r\n");
      out.write("                        <a href=\"feature.html\" class=\"dropdown-item\">에코 나눔</a>\r\n");
      out.write("                        <a href=\"team.html\" class=\"dropdown-item\">에코 지도</a>\r\n");
      out.write("                        <a href=\"testimonial.html\" class=\"dropdown-item\">에코 뉴스</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"border-start ps-4 d-none d-lg-block\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-sm p-0\"> <img src=\"/resources/client/img/LikeIcon.png\" width=\"30\"></button>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("<!-- Navbar End -->");
      out.write("\r\n");
      out.write("	<!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Page Header Start -->\r\n");
      out.write("	<div class=\"container-fluid page-header py-5 mb-5 wow fadeIn\"\r\n");
      out.write("		data-wow-delay=\"0.1s\">\r\n");
      out.write("		<div class=\"container text-center py-5\">\r\n");
      out.write("			<h1 class=\"display-3 text-white mb-4 animated slideInDown\">기부</h1>\r\n");
      out.write("			<nav aria-label=\"breadcrumb animated slideInDown\">\r\n");
      out.write("				<ol class=\"breadcrumb justify-content-center mb-0\">\r\n");
      out.write("					<li class=\"breadcrumb-item\"><a href=\"/donation/donationMain\">진행중인\r\n");
      out.write("							기부</a></li>\r\n");
      out.write("					<li class=\"breadcrumb-item\"><a href=\"/donation/postscriptMain\">기부\r\n");
      out.write("							후기</a></li>\r\n");
      out.write("				</ol>\r\n");
      out.write("			</nav>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Page Header End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- 진행중인 후원 -->\r\n");
      out.write("	<div class=\"container-xxl py-5\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!--검색하기-->\r\n");
      out.write("			<div class=\"row gx-4\">\r\n");
      out.write("				<div align=\"right\">\r\n");
      out.write("					<select id=\"sort\" name=\"sort\">\r\n");
      out.write("						<option value=\"0\">최신 순</option>\r\n");
      out.write("						<option value=\"1\">모집 금액 순</option>\r\n");
      out.write("						<option value=\"2\">기부 참여자 순</option>\r\n");
      out.write("						<option value=\"3\">종료 임박 순</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<p></p>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row gx-4\" >\r\n");
      out.write("				<form id=\"app1\">\r\n");
      out.write("					<!-- 레코드 한 줄 -->\r\n");
      out.write("					<!-- RestChatterController에서 chatterServiceList에 담긴 만큼 반복-->\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("					<template v-for=\"(dcontents, i) in currentList\">\r\n");
      out.write("						<donation :key=\"dcontents.dcontents_idx\" :num=\"num-i\"\r\n");
      out.write("							:obj=\"dcontents\" />\r\n");
      out.write("					</template>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- 레코드 한 줄 -->\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row gx-4\" align=\"right\">\r\n");
      out.write("				<!-- 페이징 처리 -->\r\n");
      out.write("				<div class=\"col-lg-11 grid-margin stretch-card\" >\r\n");
      out.write("					<div class=\"dataTables_paginate paging_simple_numbers\"\r\n");
      out.write("						id=\"zero_config_paginate\" >\r\n");
      out.write("						<ul class=\"pagination\" style=\"float: none; margin: 0 auto\" >\r\n");
      out.write("							<li class=\"paginate_button page-item active\" id=\"paging-area\" >\r\n");
      out.write("								<!--넘버링들어올곳-->\r\n");
      out.write("							</li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 페이징 처리 -->\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 진행중인 후원 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer Start -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    <!-- Footer Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-dark footer mt-5 py-5 wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row g-5\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Our Office</h5>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-map-marker-alt me-3\"></i>123 Street, New York, USA</p>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-phone-alt me-3\"></i>+012 345 67890</p>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-envelope me-3\"></i>info@example.com</p>\r\n");
      out.write("                    <div class=\"d-flex pt-3\">\r\n");
      out.write("                        <a class=\"btn btn-square btn-secondary rounded-circle me-2\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-square btn-secondary rounded-circle me-2\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-square btn-secondary rounded-circle me-2\" href=\"\"><i class=\"fab fa-youtube\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-square btn-secondary rounded-circle me-2\" href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Quick Links</h5>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">About Us</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Contact Us</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Our Services</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Terms & Condition</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Support</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Business Hours</h5>\r\n");
      out.write("                    <p class=\"mb-1\">Monday - Friday</p>\r\n");
      out.write("                    <h6 class=\"text-light\">09:00 am - 07:00 pm</h6>\r\n");
      out.write("                    <p class=\"mb-1\">Saturday</p>\r\n");
      out.write("                    <h6 class=\"text-light\">09:00 am - 12:00 pm</h6>\r\n");
      out.write("                    <p class=\"mb-1\">Sunday</p>\r\n");
      out.write("                    <h6 class=\"text-light\">Closed</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Newsletter</h5>\r\n");
      out.write("                    <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>\r\n");
      out.write("                    <div class=\"position-relative w-100\">\r\n");
      out.write("                        <input class=\"form-control bg-transparent w-100 py-3 ps-4 pe-5\" type=\"text\" placeholder=\"Your email\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-secondary py-2 position-absolute top-0 end-0 mt-2 me-2\">SignUp</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Copyright Start -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    <!-- Copyright Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-secondary text-body copyright py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 text-center text-md-start mb-3 mb-md-0\">\r\n");
      out.write("                    &copy; <a class=\"fw-semi-bold\" href=\"#\">Your Site Name</a>, All Right Reserved.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 text-center text-md-end\">\r\n");
      out.write("                    <!--/*** This template is free as long as you keep the footer authorâs credit link/attribution link/backlink. If you'd like to use the template without the footer authorâs credit link/attribution link/backlink, you can purchase the Credit Removal License from \"https://htmlcodex.com/credit-removal\". Thank you for your support. ***/-->\r\n");
      out.write("                    Designed By <a class=\"fw-semi-bold\" href=\"https://htmlcodex.com\">HTML Codex</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Copyright End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- Copyright End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Back to Start -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    <!-- Back to Top -->\r\n");
      out.write("    <a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top\"><i class=\"bi bi-arrow-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("	<!-- Back to End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer link Start -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- challenge Detail Start -->\r\n");
      out.write("	 <!-- Js Plugins -->\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery-ui.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/mixitup.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery.countdown.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery.slicknav.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/main.js\"></script>\r\n");
      out.write("   	<!-- challenge Detail End -->\r\n");
      out.write("   	\r\n");
      out.write("	<!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/wow/wow.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/counterup/counterup.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/parallax/parallax.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/lightbox/js/lightbox.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"/resources/client/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Summernote -->\r\n");
      out.write("	<script src=\"/resources/client/plugins/summernote/summernote-bs4.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- Vue -->\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js\"></script>\r\n");
      out.write("\r\n");
      out.write("	<!-- Footer link End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- -------------------------------------------------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\" src=\"/resources/js/Pager.js\"></script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("let pager = new Pager(); //인스턴스 생성\r\n");
      out.write("let currentPage=1;//현재 보고 있는 페이지\r\n");
      out.write("\r\n");
      out.write("let dDay;\r\n");
      out.write("\r\n");
      out.write("let app1;\r\n");
      out.write("let key=0;\r\n");
      out.write("\r\n");
      out.write("function day(){\r\n");
      out.write("	let yy=(json.dcontents_endday).subString(0, 4);\r\n");
      out.write("	let mm=(json.dcontents_endday).subString(5, 6);\r\n");
      out.write("	let dd=(json.dcontents_endday).subString(7, 8);\r\n");
      out.write("	dDay=dateManager.dDay(2023, 03, 30);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("const donation={\r\n");
      out.write("	template:`\r\n");
      out.write("        <div class=\"wow fadeInUp\" data-wow-delay=\"0.1s\" id=\"contents\">\r\n");
      out.write("        <div class=\"product-item\">\r\n");
      out.write("        <div class=\"position-relative\">\r\n");
      out.write("        	<img class=\"img-fluid\" :src=\"'/resources/data/donation/'+json.dcontents_thumimg\" id=\"thumimg\">\r\n");
      out.write("        <div class=\"product-overlay\" id=\"product-overlay\">\r\n");
      out.write("            <a href=\"#\"><img src=\"/resources/client/img/LikeIcon.png\" width=\"30\" href=\"\" ></a>\r\n");
      out.write("        </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    <div class=\"text-center p-4\">\r\n");
      out.write("	        <span class=\"text-primary me-1\">17% 달성</span><span>모집된 금액</span><span id=\"dday\"></span>\r\n");
      out.write("	        <a class=\"d-block h5\" v-on:click=\"getDetail(json.dcontents_idx)\">{{json.dcontents_title}}</a>\r\n");
      out.write("	        <span class=\"text\">{{json.dcontents_writer}}</span>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	`,\r\n");
      out.write("	props:[\"obj\", \"num\"], //props 오직 외부에서 전달되는 데이터 받기 위함\r\n");
      out.write("	data(){ //자바로 비유하면 인스턴스 변수영역 \r\n");
      out.write("		return{\r\n");
      out.write("			json:this.obj,\r\n");
      out.write("			n:this.num\r\n");
      out.write("		};\r\n");
      out.write("	},\r\n");
      out.write("	methods:{\r\n");
      out.write("		getDetail(idx){\r\n");
      out.write("			location.href=\"/donation/donationContent?dcontents_idx=\"+idx\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("app1=new Vue({\r\n");
      out.write("	el:\"#app1\",\r\n");
      out.write("	components:{\r\n");
      out.write("		donation\r\n");
      out.write("	},\r\n");
      out.write("	data:{\r\n");
      out.write("		count:5,\r\n");
      out.write("		dcontentsList:[], //전체배열\r\n");
      out.write("		currentList:[], //페이지당 보여질 배열\r\n");
      out.write("		num:0//페이지당 시작 번호를 뷰 컴포넌트에서 접근할 수 있도록...\r\n");
      out.write("	}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function pageLink(n){//원하는 페이지만 넘겨받기\r\n");
      out.write("	//서버에서 가져온 데이터를 대상으로 페이징 로직을 적용해보기\r\n");
      out.write("	pager.init(app1.dcontentsList, n);\r\n");
      out.write("	\r\n");
      out.write("	app1.num=pager.num;\r\n");
      out.write("	//넘겨받은 페이지 번호를 이용하여, 해당 페이지에 보여질 배열을 생성\r\n");
      out.write("	//currentList에 대입 (Vue의 변수인 currentList만 제어하면 디자인은 자동으로 변경)\r\n");
      out.write("	\r\n");
      out.write("	app1.currentList.splice(0, app1.currentList.length);//싹 비우고\r\n");
      out.write("	\r\n");
      out.write("	//채워넣기\r\n");
      out.write("	for(let i=pager.curPos; i<pager.curPos+pager.pageSize;i++){	\r\n");
      out.write("		//num이 1보다 작아지면 멈춤\r\n");
      out.write("		if(pager.num<1) break;\r\n");
      out.write("		pager.num--;\r\n");
      out.write("		\r\n");
      out.write("		//전체 배열에서, 일부 배열로 옮겨심기\r\n");
      out.write("		app1.currentList.push(app1.dcontentsList[i]);\r\n");
      out.write("		console.log(\"currentList는\", app1.currentList);\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//서버에서 상품목록 가져오기\r\n");
      out.write("function getList(){\r\n");
      out.write("	$.ajax({\r\n");
      out.write("		url:\"/rest/donationList?option_idx=\"+($('select[name=sort] option:selected').val()), \r\n");
      out.write("		type:\"get\",\r\n");
      out.write("		success:function(result, status, xhr){\r\n");
      out.write("			//서버에서 가져온 json배열을 뷰의 템블릿이 바라보고 있는 productList에 대입하면 \r\n");
      out.write("			//디자인은 알아서 변경된다.(개발자는 데이터 제어에만 집중하면 된다, 디자인 신경 X)\r\n");
      out.write("			app1.dcontentsList=result;\r\n");
      out.write("			console.log(result);\r\n");
      out.write("			\r\n");
      out.write("			//pageLink(현재페이지); //페이징 처리 계산 수행\r\n");
      out.write("			pageLink(currentPage); //페이징 처리 계산 수행\r\n");
      out.write("			//프로그램 가동하자마자 현재 페이지는 ? currentPage\r\n");
      out.write("					\r\n");
      out.write("			//넘버링 출력(1~10, 11~20)\r\n");
      out.write("			\r\n");
      out.write("			for(let i=pager.firstPage;i<pager.lastPage;i++){\r\n");
      out.write("				if(i>pager.totalPage) break;//내가 가진 페이지수를 넘어서면 반복문 빠져나오기\r\n");
      out.write("				$(\"#paging-area\").append(\"<a href='javascript:pageLink(\"+i+\")' aria-controls='zero_config' data-dt-idx='1' tabindex='0' class='page-link'>\"+i+\"</a>\")\r\n");
      out.write("\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("	//기부 리스트 가져오기\r\n");
      out.write("	getList();\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
