/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-29 15:53:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.client.community;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.friendly.eco.domain.Mem;
import com.friendly.eco.domain.ChatterComments;
import com.friendly.eco.domain.Chatter;
import java.util.List;
import com.friendly.eco.util.PageManager;
import com.friendly.eco.model.community.MybatisChatterDAO;
import com.friendly.eco.domain.Mem;

public final class chatterDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/views/client/community/../inc/capyright.jsp", Long.valueOf(1679398328000L));
    _jspx_dependants.put("/WEB-INF/views/client/community/../inc/footer.jsp", Long.valueOf(1679398328000L));
    _jspx_dependants.put("/WEB-INF/views/client/community/../inc/footer_link.jsp", Long.valueOf(1680152976000L));
    _jspx_dependants.put("/WEB-INF/views/client/community/../inc/navbar.jsp", Long.valueOf(1682771237873L));
    _jspx_dependants.put("/WEB-INF/views/client/community/../inc/back_to_top.jsp", Long.valueOf(1679398328000L));
    _jspx_dependants.put("/WEB-INF/views/client/community/../inc/header_link.jsp", Long.valueOf(1680152882000L));
    _jspx_dependants.put("/WEB-INF/views/client/community/../inc/spinner.jsp", Long.valueOf(1679398328000L));
    _jspx_dependants.put("/WEB-INF/views/client/community/../inc/topbar.jsp", Long.valueOf(1680176358000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.friendly.eco.domain.ChatterComments");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.friendly.eco.model.community.MybatisChatterDAO");
    _jspx_imports_classes.add("com.friendly.eco.domain.Chatter");
    _jspx_imports_classes.add("com.friendly.eco.util.PageManager");
    _jspx_imports_classes.add("com.friendly.eco.domain.Mem");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	//getAttribute : 서버가 다른 서버에서 요청의 값을 전달받음
	Mem mem2 = (Mem)request.getAttribute("mem");
	Chatter chatter = (Chatter)request.getAttribute("chatter");
	ChatterComments chatterComments = (ChatterComments)request.getAttribute("chatterComments");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<title>에코수다</title>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<!-- header_link Start -->\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("    <title>EcoEco</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- challenge detail  Start-->\r\n");
      out.write("	<!-- Google Font -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Cookie&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	 <!-- Css Styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/font-awesome.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/elegant-icons.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/jquery-ui.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/magnific-popup.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/owl.carousel.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/slicknav.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/style.css\" type=\"text/css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- challenge detail  End-->\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@700&family=Open+Sans:wght@400;500;600&display=swap\" rel=\"stylesheet\">   \r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"/resources/client/lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/resources/client/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/resources/client/lib/lightbox/css/lightbox.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"/resources/client/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"/resources/client/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- summernote -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/client/plugins/summernote/summernote-bs4.min.css\">\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<!-- header_link End -->\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<!-- 기본 템플릿 설정과 충돌함, 호버 효과는 포기하자!\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("	 -->\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#detail {\r\n");
      out.write("	overflow: auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Spinner Start -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <!-- Spinner Start -->\r\n");
      out.write("    <div id=\"spinner\" class=\"show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center\">\r\n");
      out.write("        <div class=\"spinner-border text-primary\" role=\"status\" style=\"width: 3rem; height: 3rem;\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Topbar Start -->\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Topbar Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-dark px-0\">\r\n");
      out.write("        <div class=\"row g-0 d-none d-lg-flex\">\r\n");
      out.write("            <div class=\"col-lg-6 ps-5 text-start\">\r\n");
      out.write("                <div class=\"h-100 d-inline-flex align-items-center text-light\">\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("             <div class=\"col-lg-6 text-end\">\r\n");
      out.write("             ");
if(session.getAttribute("mem")==null){
      out.write("\r\n");
      out.write("                <a class=\"btn btn-link text-light\" id=\"a_login\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                <div class=\"h-100 bg-secondary d-inline-flex align-items-center text-dark py-2 px-4\">\r\n");
      out.write("                    <a href=\"#\" id=\"bt_goRegist\"><span class=\"me-2 fw-semi-bold\">회원가입</span></a>\r\n");
      out.write("              ");
}else{
      out.write("    \r\n");
      out.write("              ");

                     Mem mem=(Mem)session.getAttribute("mem");
               
      out.write("\r\n");
      out.write("                <a class=\"btn btn-link text-light\" id=\"bt_logout\"><b>Logout</b></i></a>\r\n");
      out.write("                <div class=\"h-100 bg-secondary d-inline-flex align-items-center text-dark py-2 px-4\">\r\n");
      out.write("                    <a href=\"#\" id=\"bt_goMypage\"><span class=\"me-2 fw-semi-bold\">");
      out.print(mem.getMem_id() );
      out.write("님</span></a>\r\n");
      out.write("               ");
} 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Navbar Start -->\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("<!-- Navbar Start -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5\">\r\n");
      out.write("        <a href=\"/\" class=\"navbar-brand d-flex align-items-center\">\r\n");
      out.write("            <img src=\"/resources/client/img/EcoHomeLogo.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <button type=\"button\" class=\"navbar-toggler me-0\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\r\n");
      out.write("            <div class=\"navbar-nav ms-auto p-4 p-lg-0\">\r\n");
      out.write("             \r\n");
      out.write("                <div class=\"nav-item dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link\" data-bs-toggle=\"dropdown\">소개</a>\r\n");
      out.write("                    <div class=\"dropdown-menu bg-light m-0\">\r\n");
      out.write("                        <a href=\"gallery.html\" class=\"dropdown-item\">회사소개</a>\r\n");
      out.write("                        <a href=\"team_member.jsp\" class=\"dropdown-item\">팀원소개</a>\r\n");
      out.write("                        <a href=\"feature.html\" class=\"dropdown-item\">유관기관</a>\r\n");
      out.write("                        <a href=\"team.html\" class=\"dropdown-item\">기업 후원 안내</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav-item dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link\" data-bs-toggle=\"dropdown\">챌린지</a>\r\n");
      out.write("                    <div class=\"dropdown-menu bg-light m-0\">\r\n");
      out.write("                        <a href=\"/challenge/list\" class=\"dropdown-item\">공식 챌린지</a>\r\n");
      out.write("                        <a href=\"team.html\" class=\"dropdown-item\">sns 챌린지</a>\r\n");
      out.write("                        <a href=\"testimonial.html\" class=\"dropdown-item\">콜라보 챌린지</a>\r\n");
      out.write("                        <a href=\"404.html\" class=\"dropdown-item\">유저 챌린지</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav-item dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link\" data-bs-toggle=\"dropdown\">후원</a>\r\n");
      out.write("                    <div class=\"dropdown-menu bg-light m-0\">\r\n");
      out.write("                        <a href=\"/donation/donationMain\" class=\"dropdown-item\">기부</a>\r\n");
      out.write("                        <a href=\"/funding/fundingMain\" class=\"dropdown-item\">펀딩</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav-item dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link\" data-bs-toggle=\"dropdown\">커뮤니티</a>\r\n");
      out.write("                    <div class=\"dropdown-menu bg-light m-0\">\r\n");
      out.write("                        <a href=\"/community/chatterList\" class=\"dropdown-item\">에코 수다</a>\r\n");
      out.write("                        <a href=\"/community/sharingList\" class=\"dropdown-item\">에코 나눔</a>\r\n");
      out.write("                        <a href=\"404.html\" class=\"dropdown-item\">에코 지도</a>\r\n");
      out.write("                        <a href=\"404.html\" class=\"dropdown-item\">에코 뉴스</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"border-start ps-4 d-none d-lg-block\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-sm p-0\"> <img src=\"/resources/client/img/LikeIcon.png\" width=\"30\"></button>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("<!-- Navbar End -->");
      out.write("\r\n");
      out.write("                <!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("                <!-- Page Header Start -->\r\n");
      out.write("                <div class=\"container-fluid page-header py-5 mb-5 wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <div class=\"container text-center py-5\">\r\n");
      out.write("                        <h1 class=\"display-3 text-white mb-4 animated slideInDown\">에코수다</h1>\r\n");
      out.write("                        <nav aria-label=\"breadcrumb animated slideInDown\">\r\n");
      out.write("                                <h5 class=\"text-white\">자유롭게 이야기를 나누는 공간입니다.</h5>\r\n");
      out.write("                        </nav>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Page Header End -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <h3 class=\"card-title\" style=\"padding: 50px 0 25px 0\">상세내용</h3>\r\n");
      out.write("\r\n");
      out.write("                        <!-- 상세 보기 -->\r\n");
      out.write("                        <form id=\"form1\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"chatter_idx\" value=\"");
      out.print(chatter.getChatter_idx());
      out.write("\">\r\n");
      out.write("                            <input type=\"hidden\" name=\"mem_idx\" value=\"");
      out.print(chatter.getChatter_idx());
      out.write("\">\r\n");
      out.write("                            <!--이자리에 닉네임으로 바꾸기~~~~~~~-------------------------------------------------->\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-lg-12\" style=\"float: none; margin: 0 auto; padding: 0 0 0 0\">\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div class=\"basic-list-group\">\r\n");
      out.write("                                            <ul class=\"list-group\">\r\n");
      out.write("                                                <li class=\"list-group-item active\">\r\n");
      out.write("                                                    <div class=\"row\" style=\"padding: 0px 30px 0px 30px;\">\r\n");
      out.write("                                                        <label class=\"col-sm-8 col-form-label\" style=\"vertical-align: middle; color: white\"> 제리 </label> \r\n");
      out.write("                                                        <label class=\"col-sm-1 col-form-label\" style=\"vertical-align: middle; color: white\" align=\"right\"> \r\n");
      out.write("                                                            조회수 : ");
      out.print(chatter.getChatter_hits());
      out.write("\r\n");
      out.write("                                                        </label> \r\n");
      out.write("                                                        <label class=\"col-sm-3 col-form-label\" style=\"vertical-align: middle; aline: right; color: white\" align=\"right\"> \r\n");
      out.write("                                                            등록일 : ");
      out.print(chatter.getChatter_regdate());
      out.write("\r\n");
      out.write("                                                        </label>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li class=\"list-group-item\">\r\n");
      out.write("                                                    <div style=\"padding: 10px 30px 10px 30px;\">\r\n");
      out.write("                                                        <h5>\r\n");
      out.write("                                                            ");
      out.print(chatter.getChatter_title());
      out.write("\r\n");
      out.write("                                                        </h5>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li class=\"list-group-item\">\r\n");
      out.write("                                               \r\n");
      out.write("                                                    <div style=\"padding: 10px 30px 10px 30px;\" id=\"detail\">\r\n");
      out.write("                                                        ");
      out.print(chatter.getChatter_detail());
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                        <!-- 상세 보기 -->\r\n");
      out.write("\r\n");
      out.write("                        <!-- 버튼 -->\r\n");
      out.write("                        <div class=\"col \" align=\"right\" style=\"padding: 0px 15px 0px 0px;\">\r\n");
      out.write("                            <div class=\"btn-group\" role=\"group\" aria-label=\"기본 예\">\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-secondary\" id=\"bt_edit\">\r\n");
      out.write("                                    <font style=\"vertical-align: inherit;\">\r\n");
      out.write("                                        <font style=\"vertical-align: inherit;\">수정</font>\r\n");
      out.write("                                    </font>\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-secondary\" id=\"bt_delete\">\r\n");
      out.write("                                    <font style=\"vertical-align: inherit;\">\r\n");
      out.write("                                        <font style=\"vertical-align: inherit;\">삭제</font>\r\n");
      out.write("                                    </font>\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <button type=\"button\" class=\"btn btn-secondary\" id=\"bt_list\">\r\n");
      out.write("                                    <font style=\"vertical-align: inherit;\">\r\n");
      out.write("                                        <font style=\"vertical-align: inherit;\">목록</font>\r\n");
      out.write("                                    </font>\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 버튼 -->\r\n");
      out.write("\r\n");
      out.write("                        <!-- 댓글 목록 -->\r\n");
      out.write("                        <div class=\"content-body\" style=\"float: none; margin: 0 auto; padding: 15px\">\r\n");
      out.write("                        <form id=\"form2\">\r\n");
      out.write("                            <div class=\"container-fluid\">\r\n");
      out.write("                                <div class=\"row page-titles mx-0\">\r\n");
      out.write("                                    <div class=\"col-sm-6 p-md-0\">\r\n");
      out.write("                                        <h4>댓글</h4>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- row -->\r\n");
      out.write("                                <div class=\"card\">\r\n");
      out.write("                                    <div class=\"card-body\">\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                            <div class=\"col-12\">\r\n");
      out.write("                                                <!-- 댓글 한 줄 -->\r\n");
      out.write("                                                <!-- 3) chatterCommentsList에 담긴 목록 수만큼 row를 생성함 (idx와 json이 키,값으로 채워짐)-->\r\n");
      out.write("                                                <template v-for=\"json in chatterCommentsList\">\r\n");
      out.write("                                                	<row :key=\"json.chattercomments_idx\" :obj=\"json\"/>\r\n");
      out.write("                                                </template>\r\n");
      out.write("                                                <!-- 댓글 한 줄 -->\r\n");
      out.write("\r\n");
      out.write("                                                <!-- 댓글 입력 폼 -->\r\n");
      out.write("                                                <div class=\"form-group pt-3\" style=\"padding: 50px 0 25px 0\">\r\n");
      out.write("                                                    <textarea class=\"form-control\" placeholder=\"댓글을 입력하세요\" id=\"chattercomments_detail\" name=\"chattercomments_detail\"\r\n");
      out.write("                                                        style=\"height: 100px; margin: 0 auto\"></textarea>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div align=\"right\">\r\n");
      out.write("                                                    <button class=\"btn btn-dark btn-sl-sm\" type=\"button\" align=\"right\" id=\"bt_CCregister\">등록</button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <!-- 댓글 입력 폼 -->\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!-- 댓글 목록 -->\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- Footer Start -->\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("    <!-- Footer Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-dark footer mt-5 py-5 wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row g-5\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Our Office</h5>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-map-marker-alt me-3\"></i>123 Street, New York, USA</p>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-phone-alt me-3\"></i>+012 345 67890</p>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-envelope me-3\"></i>info@example.com</p>\r\n");
      out.write("                    <div class=\"d-flex pt-3\">\r\n");
      out.write("                        <a class=\"btn btn-square btn-secondary rounded-circle me-2\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-square btn-secondary rounded-circle me-2\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-square btn-secondary rounded-circle me-2\" href=\"\"><i class=\"fab fa-youtube\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-square btn-secondary rounded-circle me-2\" href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Quick Links</h5>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">About Us</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Contact Us</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Our Services</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Terms & Condition</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Support</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Business Hours</h5>\r\n");
      out.write("                    <p class=\"mb-1\">Monday - Friday</p>\r\n");
      out.write("                    <h6 class=\"text-light\">09:00 am - 07:00 pm</h6>\r\n");
      out.write("                    <p class=\"mb-1\">Saturday</p>\r\n");
      out.write("                    <h6 class=\"text-light\">09:00 am - 12:00 pm</h6>\r\n");
      out.write("                    <p class=\"mb-1\">Sunday</p>\r\n");
      out.write("                    <h6 class=\"text-light\">Closed</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Newsletter</h5>\r\n");
      out.write("                    <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>\r\n");
      out.write("                    <div class=\"position-relative w-100\">\r\n");
      out.write("                        <input class=\"form-control bg-transparent w-100 py-3 ps-4 pe-5\" type=\"text\" placeholder=\"Your email\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-secondary py-2 position-absolute top-0 end-0 mt-2 me-2\">SignUp</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("                    <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!-- Copyright Start -->\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("    <!-- Copyright Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-secondary text-body copyright py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 text-center text-md-start mb-3 mb-md-0\">\r\n");
      out.write("                    &copy; <a class=\"fw-semi-bold\" href=\"#\">Your Site Name</a>, All Right Reserved.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 text-center text-md-end\">\r\n");
      out.write("                    <!--/*** This template is free as long as you keep the footer authorâs credit link/attribution link/backlink. If you'd like to use the template without the footer authorâs credit link/attribution link/backlink, you can purchase the Credit Removal License from \"https://htmlcodex.com/credit-removal\". Thank you for your support. ***/-->\r\n");
      out.write("                    Designed By <a class=\"fw-semi-bold\" href=\"https://htmlcodex.com\">HTML Codex</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Copyright End -->\r\n");
      out.write("\r\n");
      out.write("                        <!-- Copyright End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        <!-- Back to Start -->\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("    <!-- Back to Top -->\r\n");
      out.write("    <a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top\"><i class=\"bi bi-arrow-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("                            <!-- Back to End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            <!-- Footer link Start -->\r\n");
      out.write("                            ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- challenge Detail Start -->\r\n");
      out.write("	 <!-- Js Plugins -->\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery-ui.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/mixitup.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery.countdown.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery.slicknav.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/main.js\"></script>\r\n");
      out.write("   	<!-- challenge Detail End -->\r\n");
      out.write("   	\r\n");
      out.write("	<!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/wow/wow.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/counterup/counterup.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/parallax/parallax.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/lightbox/js/lightbox.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"/resources/client/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Summernote -->\r\n");
      out.write("	<script src=\"/resources/client/plugins/summernote/summernote-bs4.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- Vue -->\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js\"></script>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Footer link End -->\r\n");
      out.write("\r\n");
      out.write("	<!-- -------------------------------------------------------------------------------- -->\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("	let form2;\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	//template으로 반복문 처리함\r\n");
      out.write("	const row={\r\n");
      out.write("			template:`\r\n");
      out.write("				<div class=\"row\" style=\"border-bottom: dotted 1px; padding:15px 0 0 0\">\r\n");
      out.write("                <div class=\"col-10\" style=\"padding: 0px 30px 0px 30px;\">\r\n");
      out.write("                    <h5 class=\"text-primary\">{{chatterComments.mem_idx}}</h5>\r\n");
      out.write("                    <p class=\"mb-0\">{{chatterComments.chattercomments_regdate}}</p>\r\n");
      out.write("                    <p class=\"mt-3\">\r\n");
      out.write("                        <strong>{{chatterComments.chattercomments_detail}}</strong>\r\n");
      out.write("                    </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-2\" align=\"right\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-dark\" name=\"bt_CCDelete\" value=\"chatterComments.chattercomments_idx\" @click=\"ccDel(chatterComments)\" >삭제</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("			`, \r\n");
      out.write("			//4) row 인스턴스 생성 시 외부에서 전달되는 파라미터(json에 담긴 chatterComments)를 받아와 data로 나타냄\r\n");
      out.write("			props:['obj'],\r\n");
      out.write("			data(){\r\n");
      out.write("				return{\r\n");
      out.write("					chatterComments:this.obj\r\n");
      out.write("				};\r\n");
      out.write("			}, \r\n");
      out.write("			methods:{ //인덱스에 해당하는 댓글을 삭제함\r\n");
      out.write("				\r\n");
      out.write("				//댓글 삭제하기\r\n");
      out.write("				ccDel(json){\r\n");
      out.write("					$.ajax({\r\n");
      out.write("						url : \"/rest/community/chatter/\"+ json.chattercomments_idx,\r\n");
      out.write("						type : \"DELETE\",\r\n");
      out.write("						success : function(result, status, xhr) {\r\n");
      out.write("							alert(\"댓글 삭제 완료 :)\");\r\n");
      out.write("							ccList();\r\n");
      out.write("						},\r\n");
      out.write("						error: function(xhr, status, result){\r\n");
      out.write("							console.log(\"xhr : \",xhr);\r\n");
      out.write("							console.log(\"status : \",status);\r\n");
      out.write("							console.log(\"result : \", result);\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	form2 = new Vue({\r\n");
      out.write("		el: '#form2',\r\n");
      out.write("		components:{\r\n");
      out.write("			row\r\n");
      out.write("		},\r\n");
      out.write("		data:{\r\n");
      out.write("			chatterCommentsList:[]\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("		//삭제하기\r\n");
      out.write("		function del() {\r\n");
      out.write("			\r\n");
      out.write("			console.log(\"선택한 글번호 : \", $(\"#form1 input[name='chatter_idx']\").val());\r\n");
      out.write("\r\n");
      out.write("			//삭제 확인하기\r\n");
      out.write("			if (!confirm(\"삭제하시겠습니까?\")) {\r\n");
      out.write("				return; \r\n");
      out.write("			}\r\n");
      out.write("\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"/community/chatter/del/\"+ $(\"#form1 input[name='chatter_idx']\").val(),\r\n");
      out.write("				type : \"POST\",\r\n");
      out.write("				success : function(result, status, xhr) {\r\n");
      out.write("					alert(\"삭제 완료 :)\");\r\n");
      out.write("					location.href = \"/community/chatterList\" //목록으로 이동\r\n");
      out.write("				},\r\n");
      out.write("				error: function(xhr, status, result){\r\n");
      out.write("					console.log(\"xhr : \",xhr);\r\n");
      out.write("					console.log(\"status : \",status);\r\n");
      out.write("					console.log(\"result : \", result);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//댓글 등록하기\r\n");
      out.write("		function ccRegister(){\r\n");
      out.write("\r\n");
      out.write("			//입력값 formData로 담기(전송 대상에 이미지가 포함되기 때문)\r\n");
      out.write("			//누구.누구로 확실하게 표기해줘야 함\r\n");
      out.write("			let formData = new FormData();\r\n");
      out.write("			formData.append(\"chatter.chatter_idx\", $(\"#form1 input[name='chatter_idx']\").val());\r\n");
      out.write("			formData.append(\"mem.mem_idx\", $(\"#form1 input[name='mem_idx']\").val()); //실제 로그인 한 회원으로 수정해야 함------------------------------------\r\n");
      out.write("			formData.append(\"chattercomments_detail\", $(\"textarea[name='chattercomments_detail']\").val()); \r\n");
      out.write("\r\n");
      out.write("			console.log(\"chatter_idx : \", $(\"#form1 input[name='chatter_idx']\").val());\r\n");
      out.write("			console.log(\"mem_idx : \", $(\"#form1 input[name='mem_idx']\").val());\r\n");
      out.write("			console.log(\"chattercomments_detail : \", $(\"textarea[name='chattercomments_detail']\").val());\r\n");
      out.write("			console.log(\"formData : \", formData); \r\n");
      out.write("			\r\n");
      out.write("			//controller로 전송하기\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url: \"/rest/community/chatter/\"+ $(\"#form1 input[name='chatter_idx']\").val(),\r\n");
      out.write("				type: \"POST\",\r\n");
      out.write("				data : formData, \r\n");
      out.write("				processData : false, //쿼리 스트링화를 방지하기 위함\r\n");
      out.write("				contentType:false, // application/x-www-form~~ 사용안함\r\n");
      out.write("				success : function(result, status, xhr){\r\n");
      out.write("					console.log(\"댓글등록정보\", result.msg);\r\n");
      out.write("					alert(\"댓글 등록 완료:)\");\r\n");
      out.write("					document.getElementById(\"chattercomments_detail\").value=''; //댓글창 비우기\r\n");
      out.write("					ccList();\r\n");
      out.write("				},\r\n");
      out.write("				error: function(xhr, status, result){\r\n");
      out.write("					console.log(\"xhr : \",xhr);\r\n");
      out.write("					console.log(\"status : \",status);\r\n");
      out.write("					console.log(\"result : \", result);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//댓글 가져오기\r\n");
      out.write("		function ccList(){\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url:\"/rest/community/chatter/\"+ $(\"#form1 input[name='chatter_idx']\").val(),\r\n");
      out.write("				type:\"GET\",\r\n");
      out.write("				success:function(result, status, xhr){\r\n");
      out.write("					form2.chatterCommentsList=result; //2) 가져오기 성공한 chatterComments을 List에 담음 \r\n");
      out.write("				},\r\n");
      out.write("				error:function(xhr, status, result){\r\n");
      out.write("					console.log(\"xhr : \", xhr);\r\n");
      out.write("					console.log(\"status : \", status);\r\n");
      out.write("					console.log(\"result : \", result);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		//init\r\n");
      out.write("		$(function() {\r\n");
      out.write("			//1) 로드 시 댓글목록 가져오기\r\n");
      out.write("			//ccList에서 로드 시 가져온 댓글목록을 chatterCommentsList에 담음\r\n");
      out.write("			//form2에서 chatterCommentsList에 담긴 목록 수만큼 row를 생성함\r\n");
      out.write("			ccList();\r\n");
      out.write("\r\n");
      out.write("			//수정버튼 이벤트 연결\r\n");
      out.write("			$(\"#bt_edit\").click(\r\n");
      out.write("					function() {\r\n");
      out.write("						//수정폼 이동\r\n");
      out.write("						location.href=\"chatterEdit?chatter_idx=\"+$(\"#form1 input[name='chatter_idx']\").val();\r\n");
      out.write("					});\r\n");
      out.write("			\r\n");
      out.write("			//삭제버튼 이벤트 연결\r\n");
      out.write("			$(\"#bt_delete\").click(function() {\r\n");
      out.write("				del();\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			//목록버튼 이벤트 연결\r\n");
      out.write("			$(\"#bt_list\").click(function() {\r\n");
      out.write("				location.href = \"/community/chatterList\"\r\n");
      out.write("			});\r\n");
      out.write("			\r\n");
      out.write("			//댓글등록버튼 이벤트 연결\r\n");
      out.write("			$(\"#bt_CCregister\").click(function() {\r\n");
      out.write("				ccRegister();\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("			//댓글삭제버튼 이벤트 연결\r\n");
      out.write("			$(\"button[name='bt_CCDelete']\").click(function() {\r\n");
      out.write("				//var chattercomments_idx = $(this).data(\"chattercomments_idx\");\r\n");
      out.write("				//console.log(\"넘어온 var chattercomments_idx : \", chattercomments_idx);\r\n");
      out.write("				//ccDel();\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
