/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-29 15:52:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.client;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.friendly.eco.domain.Mem;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(8);
    _jspx_dependants.put("/WEB-INF/views/client/./inc/back_to_top.jsp", Long.valueOf(1679398328000L));
    _jspx_dependants.put("/WEB-INF/views/client/./inc/spinner.jsp", Long.valueOf(1679398328000L));
    _jspx_dependants.put("/WEB-INF/views/client/./inc/footer.jsp", Long.valueOf(1679398328000L));
    _jspx_dependants.put("/WEB-INF/views/client/./inc/topbar.jsp", Long.valueOf(1680176358000L));
    _jspx_dependants.put("/WEB-INF/views/client/./inc/capyright.jsp", Long.valueOf(1679398328000L));
    _jspx_dependants.put("/WEB-INF/views/client/./inc/header_link.jsp", Long.valueOf(1680152882000L));
    _jspx_dependants.put("/WEB-INF/views/client/./inc/navbar.jsp", Long.valueOf(1682771237873L));
    _jspx_dependants.put("/WEB-INF/views/client/./inc/footer_link.jsp", Long.valueOf(1680152976000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.friendly.eco.domain.Mem");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	<!-- header_link Start -->\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("    <title>EcoEco</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- challenge detail  Start-->\r\n");
      out.write("	<!-- Google Font -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Cookie&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700;800;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	 <!-- Css Styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/font-awesome.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/elegant-icons.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/jquery-ui.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/magnific-popup.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/owl.carousel.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/slicknav.min.css\" type=\"text/css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/shop/css/style.css\" type=\"text/css\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- challenge detail  End-->\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@700&family=Open+Sans:wght@400;500;600&display=swap\" rel=\"stylesheet\">   \r\n");
      out.write("\r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"/resources/client/lib/animate/animate.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/resources/client/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"/resources/client/lib/lightbox/css/lightbox.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"/resources/client/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"/resources/client/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- summernote -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/resources/client/plugins/summernote/summernote-bs4.min.css\">\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("	<!-- header_link End -->\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("#zzz {\r\n");
      out.write("	width: 800px;\r\n");
      out.write("	height: 600px;\r\n");
      out.write("}\r\n");
      out.write("#work {\r\n");
      out.write("	width: 800px;\r\n");
      out.write("	height: 600px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- Spinner Start -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <!-- Spinner Start -->\r\n");
      out.write("    <div id=\"spinner\" class=\"show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center\">\r\n");
      out.write("        <div class=\"spinner-border text-primary\" role=\"status\" style=\"width: 3rem; height: 3rem;\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Topbar Start -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Topbar Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-dark px-0\">\r\n");
      out.write("        <div class=\"row g-0 d-none d-lg-flex\">\r\n");
      out.write("            <div class=\"col-lg-6 ps-5 text-start\">\r\n");
      out.write("                <div class=\"h-100 d-inline-flex align-items-center text-light\">\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("             <div class=\"col-lg-6 text-end\">\r\n");
      out.write("             ");
if(session.getAttribute("mem")==null){
      out.write("\r\n");
      out.write("                <a class=\"btn btn-link text-light\" id=\"a_login\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                <div class=\"h-100 bg-secondary d-inline-flex align-items-center text-dark py-2 px-4\">\r\n");
      out.write("                    <a href=\"#\" id=\"bt_goRegist\"><span class=\"me-2 fw-semi-bold\">회원가입</span></a>\r\n");
      out.write("              ");
}else{
      out.write("    \r\n");
      out.write("              ");

                     Mem mem=(Mem)session.getAttribute("mem");
               
      out.write("\r\n");
      out.write("                <a class=\"btn btn-link text-light\" id=\"bt_logout\"><b>Logout</b></i></a>\r\n");
      out.write("                <div class=\"h-100 bg-secondary d-inline-flex align-items-center text-dark py-2 px-4\">\r\n");
      out.write("                    <a href=\"#\" id=\"bt_goMypage\"><span class=\"me-2 fw-semi-bold\">");
      out.print(mem.getMem_id() );
      out.write("님</span></a>\r\n");
      out.write("               ");
} 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Topbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Navbar Start -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<!-- Navbar Start -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5\">\r\n");
      out.write("        <a href=\"/\" class=\"navbar-brand d-flex align-items-center\">\r\n");
      out.write("            <img src=\"/resources/client/img/EcoHomeLogo.png\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <button type=\"button\" class=\"navbar-toggler me-0\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarCollapse\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarCollapse\">\r\n");
      out.write("            <div class=\"navbar-nav ms-auto p-4 p-lg-0\">\r\n");
      out.write("             \r\n");
      out.write("                <div class=\"nav-item dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link\" data-bs-toggle=\"dropdown\">소개</a>\r\n");
      out.write("                    <div class=\"dropdown-menu bg-light m-0\">\r\n");
      out.write("                        <a href=\"gallery.html\" class=\"dropdown-item\">회사소개</a>\r\n");
      out.write("                        <a href=\"team_member.jsp\" class=\"dropdown-item\">팀원소개</a>\r\n");
      out.write("                        <a href=\"feature.html\" class=\"dropdown-item\">유관기관</a>\r\n");
      out.write("                        <a href=\"team.html\" class=\"dropdown-item\">기업 후원 안내</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav-item dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link\" data-bs-toggle=\"dropdown\">챌린지</a>\r\n");
      out.write("                    <div class=\"dropdown-menu bg-light m-0\">\r\n");
      out.write("                        <a href=\"/challenge/list\" class=\"dropdown-item\">공식 챌린지</a>\r\n");
      out.write("                        <a href=\"team.html\" class=\"dropdown-item\">sns 챌린지</a>\r\n");
      out.write("                        <a href=\"testimonial.html\" class=\"dropdown-item\">콜라보 챌린지</a>\r\n");
      out.write("                        <a href=\"404.html\" class=\"dropdown-item\">유저 챌린지</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav-item dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link\" data-bs-toggle=\"dropdown\">후원</a>\r\n");
      out.write("                    <div class=\"dropdown-menu bg-light m-0\">\r\n");
      out.write("                        <a href=\"/donation/donationMain\" class=\"dropdown-item\">기부</a>\r\n");
      out.write("                        <a href=\"/funding/fundingMain\" class=\"dropdown-item\">펀딩</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"nav-item dropdown\">\r\n");
      out.write("                    <a href=\"#\" class=\"nav-link\" data-bs-toggle=\"dropdown\">커뮤니티</a>\r\n");
      out.write("                    <div class=\"dropdown-menu bg-light m-0\">\r\n");
      out.write("                        <a href=\"/community/chatterList\" class=\"dropdown-item\">에코 수다</a>\r\n");
      out.write("                        <a href=\"/community/sharingList\" class=\"dropdown-item\">에코 나눔</a>\r\n");
      out.write("                        <a href=\"404.html\" class=\"dropdown-item\">에코 지도</a>\r\n");
      out.write("                        <a href=\"404.html\" class=\"dropdown-item\">에코 뉴스</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"border-start ps-4 d-none d-lg-block\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-sm p-0\"> <img src=\"/resources/client/img/LikeIcon.png\" width=\"30\"></button>\r\n");
      out.write("               \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("<!-- Navbar End -->");
      out.write("\r\n");
      out.write("    <!-- Navbar End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Carousel Start -->\r\n");
      out.write("    <div class=\"container-fluid px-0 mb-5\">\r\n");
      out.write("        <div id=\"header-carousel\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("            <div class=\"carousel-inner\">\r\n");
      out.write("                <div class=\"carousel-item active\">\r\n");
      out.write("                    <img class=\"w-100\" src=\"/resources/client/img/해양.jpg\" alt=\"Image\" id=\"zzz\">\r\n");
      out.write("                    <div class=\"carousel-caption\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-start\">\r\n");
      out.write("                                <div class=\"col-lg-8 text-start\">\r\n");
      out.write("                                    <p class=\"fs-4 text-white\">해양환경보호단체</p>\r\n");
      out.write("                                    <h1 class=\"display-1 text-white mb-5 animated slideInRight\">위기의 바다를 함께 지켜주세요</h1>\r\n");
      out.write("                                    <!-- <a href=\"\" class=\"btn btn-secondary rounded-pill py-3 px-5 animated slideInRight\">Explore More</a> -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"carousel-item\">\r\n");
      out.write("                    <img class=\"w-100\" src=\"/resources/client/img/나무.jpg\" alt=\"Image\"  id=\"work\">\r\n");
      out.write("                    <div class=\"carousel-caption\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-end\">\r\n");
      out.write("                                <div class=\"col-lg-8 text-end\">\r\n");
      out.write("                                    <p class=\"fs-4 text-white\">국제 나무의 날</p>\r\n");
      out.write("                                    <h1 class=\"display-1 text-white mb-5 animated slideInRight\">함께하는 나무 심기</h1>\r\n");
      out.write("                                    <!-- <a href=\"\" class=\"btn btn-secondary rounded-pill py-3 px-5 animated slideInLeft\">Explore More</a> -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#header-carousel\"\r\n");
      out.write("                data-bs-slide=\"prev\">\r\n");
      out.write("                <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#header-carousel\"\r\n");
      out.write("                data-bs-slide=\"next\">\r\n");
      out.write("                <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Carousel End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Features Start -->\r\n");
      out.write("    <div class=\"container-xxl py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row g-5 align-items-center\">\r\n");
      out.write("                <div class=\"col-lg-12\">\r\n");
      out.write("                    <div class=\"rounded overflow-hidden\">\r\n");
      out.write("                        <div class=\"row g-0\">\r\n");
      out.write("                            <div class=\"col-sm-3 wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                                <div class=\"text-center bg-primary py-5 px-4\">\r\n");
      out.write("                                    <h1 class=\"display-6 text-white\" data-toggle=\"counter-up\">25</h1>\r\n");
      out.write("                                    <span class=\"fs-5 fw-semi-bold text-secondary\">기부 참여</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-sm-3 wow fadeIn\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                                <div class=\"text-center bg-secondary py-5 px-4\">\r\n");
      out.write("                                    <h1 class=\"display-6\" data-toggle=\"counter-up\">183</h1>\r\n");
      out.write("                                    <span class=\"fs-5 fw-semi-bold text-primary\">기부 금액</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-sm-3 wow fadeIn\" data-wow-delay=\"0.7s\">\r\n");
      out.write("                                <div class=\"text-center bg-primary py-5 px-4\">\r\n");
      out.write("                                    <h1 class=\"display-6 text-white\" data-toggle=\"counter-up\">51940</h1>\r\n");
      out.write("                                    <span class=\"fs-5 fw-semi-bold text-secondary\">펀딩 참여</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-sm-3 wow fadeIn\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                                <div class=\"text-center bg-secondary py-5 px-4\">\r\n");
      out.write("                                    <h1 class=\"display-6\" data-toggle=\"counter-up\">2619</h1>\r\n");
      out.write("                                    <span class=\"fs-5 fw-semi-bold text-primary\">펀딩 금액</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Features End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 진행중인 후원 -->\r\n");
      out.write("    <div class=\"container-xxl py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"text-center mx-auto wow fadeInUp\" data-wow-delay=\"0.1s\" style=\"max-width: 500px;\">\r\n");
      out.write("                <p class=\"section-title bg-white text-center text-primary px-3\">ECOECO</p>\r\n");
      out.write("                <a href=\"#\"><h1 class=\"mb-5\">진행중인 후원</h1></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row gx-4\">\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\" id=\"box\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"/resources/client/img/두루미.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"product-overlay\">\r\n");
      out.write("                                <a href=\"#\"><img src=\"/resources/client/img/LikeIcon.png\" width=\"30\" href=\"\" ></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"\">두루미를 지켜주세요</a>\r\n");
      out.write("                            <span class=\"text-primary me-1\">두루미보호단체</span>\r\n");
      out.write("                            <span class=\"text-decoration-line-through\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"/resources/client/img/나무심기.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"product-overlay\">\r\n");
      out.write("                               <a href=\"#\"><img src=\"/resources/client/img/LikeIcon.png\" width=\"30\" href=\"\" ></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"\">나무심기 운동</a>\r\n");
      out.write("                            <span class=\"text-primary me-1\">한국환경연합</span>\r\n");
      out.write("                            <span class=\"text-decoration-line-through\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"/resources/client/img/야생벌.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"product-overlay\">\r\n");
      out.write("                              <a href=\"#\"><img src=\"/resources/client/img/LikeIcon.png\" width=\"30\" href=\"\" ></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"\">야생벌을 구해주세요</a>\r\n");
      out.write("                            <span class=\"text-primary me-1\">벌지킴이단체</span>\r\n");
      out.write("                            <span class=\"text-decoration-line-through\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.7s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"/resources/client/img/해양오염.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"product-overlay\">\r\n");
      out.write("                              <a href=\"#\"><img src=\"/resources/client/img/LikeIcon.png\" width=\"30\" href=\"\" ></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"\">해양쓰레기 정리사업</a>\r\n");
      out.write("                            <span class=\"text-primary me-1\">해양오염연합</span>\r\n");
      out.write("                            <span class=\"text-decoration-line-through\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 진행중인 후원 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 진행중인 챌린지 -->\r\n");
      out.write("    <div class=\"container-xxl py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"text-center mx-auto wow fadeInUp\" data-wow-delay=\"0.1s\" style=\"max-width: 500px;\">\r\n");
      out.write("                <p class=\"section-title bg-white text-center text-primary px-3\">ECOECO</p>\r\n");
      out.write("                <a href=\"#\"><h1 class=\"mb-5\">진행중인 챌린지</h1></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row gx-4\">\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"/resources/client/img/메일비우기.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"product-overlay\">\r\n");
      out.write("                                <a href=\"#\"><img src=\"/resources/client/img/LikeIcon.png\" width=\"30\" href=\"\" ></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"\">매일 메일 비우기~!</a>\r\n");
      out.write("                            <span class=\"text-primary me-1\">환경지키미전</span>\r\n");
      out.write("                            <span class=\"text-decoration-line-through\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"/resources/client/img/분리수거.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"product-overlay\">\r\n");
      out.write("                               <a href=\"#\"><img src=\"/resources/client/img/LikeIcon.png\" width=\"30\" href=\"\" ></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"\">길거리 쓰레기 줍기!</a>\r\n");
      out.write("                            <span class=\"text-primary me-1\">줍줍이</span>\r\n");
      out.write("                            <span class=\"text-decoration-line-through\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"/resources/client/img/재활용.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"product-overlay\">\r\n");
      out.write("                              <a href=\"#\"><img src=\"/resources/client/img/LikeIcon.png\" width=\"30\" href=\"\" ></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"\">재활용 챌린지</a>\r\n");
      out.write("                            <span class=\"text-primary me-1\">용용이</span>\r\n");
      out.write("                            <span class=\"text-decoration-line-through\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.7s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"/resources/client/img/컵.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"product-overlay\">\r\n");
      out.write("                              <a href=\"#\"><img src=\"/resources/client/img/LikeIcon.png\" width=\"30\" href=\"\" ></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"\">컵 사용 챌린지</a>\r\n");
      out.write("                            <span class=\"text-primary me-1\">컵컵</span>\r\n");
      out.write("                            <span class=\"text-decoration-line-through\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 진행중인 챌린지 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- 진행중인 나눔 -->\r\n");
      out.write("    <div class=\"container-xxl py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"text-center mx-auto wow fadeInUp\" data-wow-delay=\"0.1s\" style=\"max-width: 500px;\">\r\n");
      out.write("                <p class=\"section-title bg-white text-center text-primary px-3\">ECOECO</p>\r\n");
      out.write("                <a href=\"#\"><h1 class=\"mb-5\">진행중인 나눔</h1></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row gx-4\">\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.1s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"/resources/client/img/자전거.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"product-overlay\">\r\n");
      out.write("                                <a href=\"#\"><img src=\"/resources/client/img/LikeIcon.png\" width=\"30\" href=\"\" ></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"\">자전거 나눔</a>\r\n");
      out.write("                            <span class=\"text-primary me-1\">따릉따릉이</span>\r\n");
      out.write("                            <span class=\"text-decoration-line-through\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.3s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"/resources/client/img/빨래.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"product-overlay\">\r\n");
      out.write("                               <a href=\"#\"><img src=\"/resources/client/img/LikeIcon.png\" width=\"30\" href=\"\" ></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"\">친환경 세제 소분</a>\r\n");
      out.write("                            <span class=\"text-primary me-1\">맑은날은세탁하는날</span>\r\n");
      out.write("                            <span class=\"text-decoration-line-through\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.5s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"/resources/client/img/아이옷.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"product-overlay\">\r\n");
      out.write("                              <a href=\"#\"><img src=\"/resources/client/img/LikeIcon.png\" width=\"30\" href=\"\" ></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"\">큰애 옷 물려줄게요</a>\r\n");
      out.write("                            <span class=\"text-primary me-1\">맑음</span>\r\n");
      out.write("                            <span class=\"text-decoration-line-through\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 col-lg-4 col-xl-3 wow fadeInUp\" data-wow-delay=\"0.7s\">\r\n");
      out.write("                    <div class=\"product-item\">\r\n");
      out.write("                        <div class=\"position-relative\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"/resources/client/img/책상.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"product-overlay\">\r\n");
      out.write("                              <a href=\"#\"><img src=\"/resources/client/img/LikeIcon.png\" width=\"30\" href=\"\" ></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"text-center p-4\">\r\n");
      out.write("                            <a class=\"d-block h5\" href=\"\">책상 가져가세요</a>\r\n");
      out.write("                            <span class=\"text-primary me-1\">이사가요</span>\r\n");
      out.write("                            <span class=\"text-decoration-line-through\"></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 진행중인 나눔 -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- 에코 지도 -->\r\n");
      out.write("    <div class=\"container-xxl py-5\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"text-center mx-auto wow fadeInUp\" data-wow-delay=\"0.1s\" style=\"max-width: 500px;\">\r\n");
      out.write("                <p class=\"section-title bg-white text-center text-primary px-3\">ECOECO</p>\r\n");
      out.write("                <a href=\"#\"><h1 class=\"mb-5\">에코 지도</h1></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"row g-4\" style=\"padding:10x;\">\r\n");
      out.write("            	<!-- 목록 -->\r\n");
      out.write("	         	<div class=\"col-lg-6 col-md-6 wow fadeInUp\" style=\"padding:10x\" data-wow-delay=\"0.1s\">\r\n");
      out.write("					<div class=\"card\">\r\n");
      out.write("					<div class=\"card-header\">\r\n");
      out.write("					<div class=\"input-group input-group-sm\" style=\"width: 150px;\">\r\n");
      out.write("					<input type=\"text\" name=\"table_search\" class=\"form-control float-right\" placeholder=\"Search\">\r\n");
      out.write("					<div class=\"input-group-append\">\r\n");
      out.write("					<button type=\"submit\" class=\"btn btn-default\">\r\n");
      out.write("					<i class=\"fas fa-search\"></i>\r\n");
      out.write("					</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"card-body table-responsive p-0\" style=\"height: 300px;\">\r\n");
      out.write("					<table class=\"table table-head-fixed text-nowrap\">\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<th>No</th>\r\n");
      out.write("						<th>상호명</th>\r\n");
      out.write("						<th>주소</th>\r\n");
      out.write("						<th>별점</th>\r\n");
      out.write("						<th>내용</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td>1</td>\r\n");
      out.write("						<td>환경운동 </td>\r\n");
      out.write("						<td>서울 용산구 한강대로76길 7</td>\r\n");
      out.write("						<td><span class=\"tag tag-danger\">5</span></td>\r\n");
      out.write("						<td>환경운동</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td>2</td>\r\n");
      out.write("						<td>용산나눔의집 </td>\r\n");
      out.write("						<td>서울 용산구 새마을로 47</td>\r\n");
      out.write("						<td><span class=\"tag tag-danger\">4</span></td>\r\n");
      out.write("						<td>환경</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td>3</td>\r\n");
      out.write("						<td>용산구재활용센터</td>\r\n");
      out.write("						<td>서울 용산구 한강대로67길 22-20</td>\r\n");
      out.write("						<td><span class=\"tag tag-danger\">4.5</span></td>\r\n");
      out.write("						<td>리사이클링</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td>4</td>\r\n");
      out.write("						<td>중고가전재활용센터 </td>\r\n");
      out.write("						<td>서울 용산구 효창원로 99</td>\r\n");
      out.write("						<td><span class=\"tag tag-danger\">3</span></td>\r\n");
      out.write("						<td>재활용</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td>5</td>\r\n");
      out.write("						<td>(주)메트로리사이클링 </td>\r\n");
      out.write("						<td>서울 마포구 새창로 40</td>\r\n");
      out.write("						<td><span class=\"tag tag-danger\">4</span></td>\r\n");
      out.write("						<td>리사이클링</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("						<td>6</td>\r\n");
      out.write("						<td>원불교환경연대 </td>\r\n");
      out.write("						<td>서울 용산구 한강대로40가길 24</td>\r\n");
      out.write("						<td><span class=\"tag tag-danger\">4.3</span></td>\r\n");
      out.write("						<td>연대</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</tbody>\r\n");
      out.write("					</table>\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("	            <!-- 목록 -->\r\n");
      out.write("	            \r\n");
      out.write("	            <!-- 지도 -->\r\n");
      out.write("	            <div class=\"col-lg-6 col-md-6 wow fadeInUp\" style=\"padding:10x\" data-wow-delay=\"0.1s\">\r\n");
      out.write("	            <iframe class=\"w-100 rounded\" src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd\" frameborder=\"0\" style=\"min-height: 350px; border:0;\" allowfullscreen=\"\" aria-hidden=\"false\" tabindex=\"0\"></iframe>\r\n");
      out.write("	            </div>\r\n");
      out.write("	            <!-- 지도 -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 에코 지도 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer Start -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <!-- Footer Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-dark footer mt-5 py-5 wow fadeIn\" data-wow-delay=\"0.1s\">\r\n");
      out.write("        <div class=\"container py-5\">\r\n");
      out.write("            <div class=\"row g-5\">\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Our Office</h5>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-map-marker-alt me-3\"></i>123 Street, New York, USA</p>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-phone-alt me-3\"></i>+012 345 67890</p>\r\n");
      out.write("                    <p class=\"mb-2\"><i class=\"fa fa-envelope me-3\"></i>info@example.com</p>\r\n");
      out.write("                    <div class=\"d-flex pt-3\">\r\n");
      out.write("                        <a class=\"btn btn-square btn-secondary rounded-circle me-2\" href=\"\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-square btn-secondary rounded-circle me-2\" href=\"\"><i class=\"fab fa-facebook-f\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-square btn-secondary rounded-circle me-2\" href=\"\"><i class=\"fab fa-youtube\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-square btn-secondary rounded-circle me-2\" href=\"\"><i class=\"fab fa-linkedin-in\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Quick Links</h5>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">About Us</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Contact Us</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Our Services</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Terms & Condition</a>\r\n");
      out.write("                    <a class=\"btn btn-link\" href=\"\">Support</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Business Hours</h5>\r\n");
      out.write("                    <p class=\"mb-1\">Monday - Friday</p>\r\n");
      out.write("                    <h6 class=\"text-light\">09:00 am - 07:00 pm</h6>\r\n");
      out.write("                    <p class=\"mb-1\">Saturday</p>\r\n");
      out.write("                    <h6 class=\"text-light\">09:00 am - 12:00 pm</h6>\r\n");
      out.write("                    <p class=\"mb-1\">Sunday</p>\r\n");
      out.write("                    <h6 class=\"text-light\">Closed</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-md-6\">\r\n");
      out.write("                    <h5 class=\"text-white mb-4\">Newsletter</h5>\r\n");
      out.write("                    <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>\r\n");
      out.write("                    <div class=\"position-relative w-100\">\r\n");
      out.write("                        <input class=\"form-control bg-transparent w-100 py-3 ps-4 pe-5\" type=\"text\" placeholder=\"Your email\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn btn-secondary py-2 position-absolute top-0 end-0 mt-2 me-2\">SignUp</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Copyright Start -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <!-- Copyright Start -->\r\n");
      out.write("    <div class=\"container-fluid bg-secondary text-body copyright py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 text-center text-md-start mb-3 mb-md-0\">\r\n");
      out.write("                    &copy; <a class=\"fw-semi-bold\" href=\"#\">Your Site Name</a>, All Right Reserved.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 text-center text-md-end\">\r\n");
      out.write("                    <!--/*** This template is free as long as you keep the footer authorâs credit link/attribution link/backlink. If you'd like to use the template without the footer authorâs credit link/attribution link/backlink, you can purchase the Credit Removal License from \"https://htmlcodex.com/credit-removal\". Thank you for your support. ***/-->\r\n");
      out.write("                    Designed By <a class=\"fw-semi-bold\" href=\"https://htmlcodex.com\">HTML Codex</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Copyright End -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Copyright End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Back to Top -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <!-- Back to Top -->\r\n");
      out.write("    <a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square rounded-circle back-to-top\"><i class=\"bi bi-arrow-up\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- JavaScript Libraries -->\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- challenge Detail Start -->\r\n");
      out.write("	 <!-- Js Plugins -->\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery-ui.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/mixitup.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery.countdown.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery.slicknav.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("    <script src=\"/resources/shop/js/main.js\"></script>\r\n");
      out.write("   	<!-- challenge Detail End -->\r\n");
      out.write("   	\r\n");
      out.write("	<!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/wow/wow.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/counterup/counterup.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/parallax/parallax.min.js\"></script>\r\n");
      out.write("    <script href=\"/resources/client/lib/lightbox/js/lightbox.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"/resources/client/js/main.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Summernote -->\r\n");
      out.write("	<script src=\"/resources/client/plugins/summernote/summernote-bs4.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<!-- Vue -->\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    	$(function(){\r\n");
      out.write("    		$(\"#a_login\").click(function(){\r\n");
      out.write("    			location.href = \"/member/login\";\r\n");
      out.write("    		});\r\n");
      out.write("    	});\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
